/* eslint-disable no-template-curly-in-string */
// Do not edit this file - edit config.json instead.

const path = require("path");

const util = require("./util");

const loadJSON = util.loadJSON;
const saveJSON = util.saveJSON;
const deepMerge = util.deepMerge;

const defaultConfig = {
    eris: {
        token: "TOKEN GOES HERE",
        id: "CHANNEL ID GOES HERE",
        topicTimeout: 10000,
        playing: "Just Cause 3 Multiplayer"
    },
    formatting: {
        discordToGame: {
            chat: "${nick}: ${message}",
            colour: "7289DA"
        },
        gameToDiscord: {
            topic: "Join the server at xxx.xxx.xxx.xxx:port | ${players}/${maxPlayers} players currently online | Current tick rate: ${jcmp.server.currentTickRate}",
            chat: "${username}: ${message}",
            death: "${username} ${(killer && killer.name ? \"was killed by \" + killer.name : \"died\")}",
            connect: "${username} connected to the server.",
            disconnect: "${username} disconnected from the server."
        }
    }
};

function getFullConfig() {
    const configPath = path.join(__dirname, "./config.json");
    const loadedConfig = loadJSON(configPath);
    const fullConfig = deepMerge(defaultConfig, loadedConfig);

    if (fullConfig.length > loadedConfig.length) {
        fullConfig.lastUpdated = (new Date()).toUTCString();
    }
    saveJSON(configPath, fullConfig);

    return fullConfig;
}

module.exports = getFullConfig;
module.exports.defaultConfig = defaultConfig;
