/* eslint-disable no-template-curly-in-string */
// IMPORTANT:
// Do not edit this file - edit config.json instead.

const path = require("path");

const util = require("./util");

const loadJSON = util.loadJSON;
const saveJSON = util.saveJSON;

const defaultConfig = {
    eris: {
        token: "TOKEN GOES HERE",
        id: "CHANNEL ID GOES HERE",
        topicTimeout: 10000,
        playing: "Just Cause 3 Multiplayer"
    },
    formatting: {
        discordToGame: {
            chat: "${nick}: ${message}",
            colour: "7289DA"
        },
        gameToDiscord: {
            topic: "Join the server at xxx.xxx.xxx.xxx:port | ${players}/${maxPlayers} players currently online | Current tick rate: ${jcmp.server.currentTickRate}",
            chat: "${username}: ${message}",
            death: "*${username} ${(killer && killer.name ? \"was killed by \" + killer.name : \"died\")}*",
            connect: "**${username} connected to the server.**",
            disconnect: "**${username} disconnected from the server.**"
        }
    }
};

function getFullConfig() {
    const configPath = path.join(__dirname, "./config.json");
    const loadedConfig = loadJSON(configPath);

    const fullConfig = { eris: {}, formatting: { discordToGame: {}, gameToDiscord: {} } };
    fullConfig.eris = Object.assign(
        defaultConfig.eris,
        loadedConfig.eris);
    fullConfig.formatting.discordToGame = Object.assign(
        defaultConfig.formatting.discordToGame,
        loadedConfig.formatting.discordToGame);
    fullConfig.formatting.gameToDiscord = Object.assign(
        defaultConfig.formatting.gameToDiscord,
        loadedConfig.formatting.gameToDiscord);

    if (fullConfig.length > loadedConfig.length
        || fullConfig.eris.length > loadedConfig.eris.length
        || fullConfig.formatting.discordToGame.length > loadedConfig.formatting.discordToGame.length
        || fullConfig.formatting.gameToDiscord.length > loadedConfig.formatting.gameToDiscord.length
    ) {
        fullConfig.lastUpdated = (new Date()).toUTCString();
    }
    saveJSON(configPath, fullConfig);

    return fullConfig;
}

module.exports = getFullConfig;
module.exports.defaultConfig = defaultConfig;
